#cloud-config
disable_root: false
ssh_pwauth: true

packages:
  - docker
  - docker.io
  - cgroupfs-mount
  - net-tools

write_files:
  - path: /tmp/swm-init.sh
    permissions: '0755'
    content: |+
{{cloud_init_script}}

runcmd:
  - bash /tmp/swm-init.sh
